deku/app1/urls.py
from django.conf.urls import url
from . import views
urlpatterns=[
    url('^tips/',views.tips,name='tips'),
    url('^tips_done/',views.tips_done,name='tips_done'),
    url('^home/',views.home,name='home'),
    url('^new/', views.new, name='new'),
    url('^add/action', views.add_action, name='add_action'),
    url('^del/action', views.del_action, name='del_action'),
    url('^d_action', views.del_action1, name='del_action1'),
    url('^done_action', views.done_action, name='done_action1'),

]

deku/deku/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app1 import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/',include('app1.urls',namespace='index')),
    url(r'^$', views.index),

]

deku/app1/models.py
from django.db import models

# Create your models here.
class tips(models.Model):
    title=models.CharField(max_length=16,default='title')
    content=models.TextField()
    level = models.IntegerField()
    type=models.IntegerField(default=0)
    def __str__(self):
       return self.title

deku/app1/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models
# Create your views here.
def index(request):
    return render(request,'app1/index.html')

def home(request):
    return render(request,'app1/home.html')


def tips(request):
    tips=models.tips.objects.filter(type=0)
    return render(request, 'app1/tips.html',{'tips':tips})
def tips_done(request):
    tips = models.tips.objects.filter(type=1)
    return render(request, 'app1/tips_done.html',{'tips':tips})
def new(request):
    return render(request,'app1/new.html')

def del_action(request):
    del_id=request.POST.get('del_id')
    tip=models.tips.objects.get(pk=del_id)
    tip.delete()
    tips = models.tips.objects.filter(type=1)
    return render(request,'app1/tips_done.html',{'tips':tips})
def del_action1(request):
    id=request.POST.get('del_id')
    t=models.tips.objects.get(pk=id)
    t.delete()
    tips = models.tips.objects.filter(type=0)
    return render(request, 'app1/tips.html', {'tips': tips})
def done_action(request):
    id=request.POST.get('done_id')
    t=models.tips.objects.get(pk=id)
    t.type=1
    t.save()
    tips = models.tips.objects.filter(type=0)
    return render(request, 'app1/tips.html', {'tips': tips})
def add_action(request):
    title=request.POST.get('title')
    content=request.POST.get('content')
    level=request.POST.get('level')
    type=request.POST.get('type')
    models.tips.objects.create(title=title,content=content,level=level,type=type)

    return render(request, 'app1/new.html')

deku/app1/templates/app1/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="{%static "css/bootstrap.css" %}" />
    <style>


    </style>
    <title>德酷便签</title>
</head>
<body>
    <nav class="nav navbar  navbar-default navbar-fixed-bottom" >
     <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand">Deku德酷</a>
            <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#ul">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse" id="ul">
           <ul class="nav navbar-nav" style="display: flex;flex-direction: row;justify-content: space-around">
            <li style="list-style: none" class="active">
                <a href="#todo" data-toggle="tab">ToDo</a>
            </li>
            <li style="list-style: none">
                <a href="#new" data-toggle="tab">New</a>
            </li>
            <li style="list-style: none">
                <a href="#done" data-toggle="tab">Done</a>
            </li>
            <li style="list-style: none">
                <a href="#about" data-toggle="tab">About</a>
            </li>
        </ul>
        </div>
    </div>
    </nav>
    <div class="tab-content">
      <div class="tab-pane fade in active" id="todo">
          <iframe src="{% url 'index:tips' %}" onload="this.height=document.documentElement.clientHeight-50" width="100%" frameborder="0" ></iframe>
      </div>
      <div class="tab-pane fade" id="new">
            <iframe src="{% url 'index:new' %}" onload="this.height=document.documentElement.clientHeight-50" width="100%" frameborder="0"></iframe>
      </div>
      <div class="tab-pane fade" id="done">
            <iframe src="{% url 'index:tips_done' %}" onload="this.height=document.documentElement.clientHeight-50" width="100%" frameborder="0"></iframe>
      </div>
      <div class="tab-pane fade" id="about">

      </div>
    </div>
<div class="container"></div>
</body>
<script type="text/javascript" src="{% static "js/jquery-3.2.1.js" %}" ></script>
<script type="text/javascript" src="{% static "js/bootstrap.js" %}" ></script>
<script type="text/javascript">


</script>
</html>

deku/app1/templates/app1/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>约战科成篮球社&德酷工作室</title>
    <link rel="stylesheet" href="{%static "css/bootstrap.css" %}" />
{#    <script type="text/javascript" src="js/jquery-3.2.1.min.js" ></script>#}
{#    <script type="text/javascript" src="js/bootstrap.min.js" ></script>#}
    
    <style>
    	.fjx{
    		display: flex;
    		flex-direction: row;
    		justify-content: space-around;
    		margin-top: 20px;
    	}
    	.fjx-i{
    		background-image: url({% static "img/1.png" %});
    		height: 10px;
    		width: 10px;
    	}
    	.wanted{
    		font-size: 44px;
    		font-family: "agency fb";
    		border: 2px solid #FFF;
    		background-image: url({% static "img/4.png" %});
    		border-radius: 10px;
    		color: #FFF;
    		animation-name:change;
    		animation-duration: 1s;
    		animation-iteration-count:infinite;
    	}
    	/*@keyframes change{
    		from{font-size: 44px;}
    		
    		to{font-size: 42px;}
    		
    	}*/
    	.wanteddiv{
    		margin-top: -30px ;
    		text-align: center;
    	}
    	.img-intro{
    		width: 100%;
    		
    	}
    	.bm-group{
    		margin-top: 100px;
    		
    	}
    	.bmtitle{
    		display: flex;
    		flex-direction: row;
    		justify-content: space-around;
    		border-bottom: 0px;
    		
    		
    	}
    	.bmtab{
    		height: 120px;
    		width: 80px;
    		border-bottom: 0px;
    		margin-top: -55px;
    	}
    	.bmtab a{
    		color:#337ab7 ;
    		height: 100%;
    		width: 100%;
    		border-radius: 10px !important;
    		border-bottom: 0px;
    		font-size: 18px;
    		font-weight: bold;
    		line-height: 280px !important;
    		
    	}
    	.bma-1{
    		background-image: url({% static "img/ys.jpg" %});
    		
    		
    	}
    	.bma-2{
    		background-image: url({% static "img/rh.jpg" %});
    		
    	}
    	.bma-3{
    		background-image: url({% static "img/hr.jpg" %});
    		
    	}
    	.bma-4{
    		background-image: url({% static "img/hj.jpg" %});
    		
    	}
    	.bm-group{
    		background: linear-gradient(to bottom,rgba(1,1,0,.4), rgba(255,0,0,0));
    		
    	}
    	.tab-content{
    		margin-top:70px;
    		
    	}
    	.tab-pane{
    		color: #fff;
    		
    	}
    	.aactive{
    		transition:transform .2s;
    		transform: scale(1.1,1.1);
    		transform-origin: center;
    		/*height: 130px !important;
    		width: 90px !important;*/
    		/*margin-left: -5px;*/
    		/*margin-top: -5px;*/
    		/*font-size: 24px !important;*/
    		box-shadow: #000 0px 1px 5px;
    		color: #fff !important;
    		
    	}
    	.summary{
    		
    		
    		width: 100%;
    		
    	}
    	.btn-join{
    		box-shadow: #31B0D5 5px 5px 10px;
    		font-size: 18px;
    		font-family: "rage italic";
    		animation-name:change2;
    		animation-duration: 1s;
    		animation-iteration-count:infinite;
    	}
    	
    	@keyframes change2{
    		from{font-size: 18px;}
    		
    		to{font-size: 20px;}
    		
    	}
    	.modal{
    		top: auto !important;
    	}
    </style>
    <script type="text/javascript">
    	
   	
   		
    </script>
</head>
<body style="background: #ddd;">
	<div class="intro" >
		<img class="img-intro" src="{% static "img/big.jpg"%}" />
		<div class="wanteddiv">
			<a href="" class="wanted" >WANTED</a>			
		</div>
	</div>
	<div class="summary">
		<div class="fjx">
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
			<div class="fjx-i"></div>
		</div>	
		<div class="bm-group">
			<ul class="nav nav-tabs bmtitle">
				<li class="active bmtab"><a class="bma-1 aactive" href="#bm-1" data-toggle="tab">组织</a></li>
				<li class="bmtab"><a class="bma-2 " href="#bm-2" data-toggle="tab">宣传</a></li>
				<li class="bmtab"><a class="bma-3" href="#bm-3" data-toggle="tab">裁判</a></li>
				<li class="bmtab"><a class="bma-4" href="#bm-4" data-toggle="tab">篮球</a></li>
			</ul>
			<div class="tab-content container">
				<div class="tab-pane fade in active" id="bm-1" >
					<h3>组织部</h3>
					<p>组织训练、组队观赛、组织集体裁判培训与讲解等为主要活动形式展开。为调动起学校里篮球爱好者的激情，为他们提供展现自己的机会，在条件允许的情况下开展有关篮球的比赛。各个干事可以为赛事做策划出点子，来决定赛事以什么样子的形式展开，并且在比赛开始前协助其他同学运输体育器材等。在比赛的时候记录比赛。</p>
					<div class="joinin" style="text-align: center;margin-bottom: 20px;margin-top: 10px;">
						<button class="btn btn-info btn-join" data-toggle="modal" data-target="#myModal">JOIN US!</button>
						<input type="hidden" value="组织部负责人(贾浩鑫)QQ" />
						<input type="hidden" value="1275917783" />
					</div>
				</div>
				<div class="tab-pane fade" id="bm-2"><h3>宣传部</h3>
					<p>负责相关篮球活动比赛的宣传以及推广，积极联系主流媒体，宣传篮球协会的各项活动不断增进与校内其他团体的沟通与交流。</p>
					<div class="joinin" style="text-align: center;margin-bottom: 20px;margin-top: 10px;">
						<button class="btn btn-info btn-join"  data-toggle="modal" data-target="#myModal">JOIN US!</button>
						<input type="hidden" value="宣传部负责人(张照阳)QQ" />
						<input type="hidden" value="1406873616" />
					</div>
				</div>
				<div class="tab-pane fade" id="bm-3"><h3>裁判部</h3>
					<p>篮球裁判对篮球比赛极为关键，主要负责学校各项篮球活动和比赛的裁判人员调度。</br>
要求要有正义感，认真负责，能坚持，能吃苦。
只要你对篮球裁判感兴趣，我们欢迎你的加入。我们会根据部员的具体课表安排免费的相关知识教学</p>
					<div class="joinin" style="text-align: center;margin-bottom: 20px;margin-top: 10px;">
						<button class="btn btn-info btn-join"  data-toggle="modal" data-target="#myModal">JOIN US!</button>
						<input type="hidden" value="裁判部负责人(梁嘉义)QQ" />
						<input type="hidden" value="954736463" />
					</div>
				</div>
				<div class="tab-pane fade" id="bm-4"><h3>篮球部</h3>
					
					<p>作为篮球协会核心部门，主要作用为发展带动学院各个院系篮球气氛，为广大爱好者提供各种交流篮球技术，培养篮球爱好的机会，活动于学院各个有篮球的角落，每个篮球部的人都有充分的机会提高发展自身的球技，以及带动身边的人喜欢篮球这项运动</p>
					<div class="joinin" style="text-align: center;margin-bottom: 20px;margin-top: 10px;">						
						<button class="btn btn-info btn-join" data-toggle="modal" data-target="#myModal">JOIN US!</button>
						<input type="hidden" value="篮球部负责人(张喆)QQ" />
						<input type="hidden" value="1030154708" />
					</div>
				</div>
			</div>			
		</div>
		
	</div>
	<div class="modal fade" id="myModal" tabindex="-1" >
		<div class="modal-content">
			<div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">加入方式</h4>
	    </div>
	    <div class="modal-body">
	        <label>社长(黄山)QQ</label><p>734460092</p>
	        <label class="bm-fzr"></label><p>734460092</p>
      	</div>
		<div class="modal-footer" style="text-align: center;">
	        <button type="button" class="btn btn-primary" data-dismiss="modal">我知道啦！</button>
	    </div>
	 	</div>
		
	</div>
</body>
<script type="text/javascript" src="{% static "js/jquery-3.2.1.js" %}" ></script>
<script type="text/javascript" src="{% static "js/bootstrap.js" %}" ></script>
	<script type="text/javascript">
    	$('.bmtab a').on('click',function(){
    		$(this).addClass('aactive').parent().siblings().children().removeClass('aactive')
    	})
    	$('.btn-join').on('click',function(){
    		var flag=$(this).next().val()
    		var fzr=$('.bm-fzr')
    		var qq=$(this).next().next().val()
    		var fzrq=$('.bm-fzr').next()
    		fzrq.text(qq)
    		fzr.text(flag)
    		
    	})
    </script>
</html>

deku/app1/templates/app1/index1.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="{%static "css/bootstrap.css" %}" />
    <title>Deku德酷</title>
    <style>


    </style>
</head>

<body style="background: url({% static "img/timg.jpg" %}) no-repeat;">

<div class="img" style="margin: 100px auto 50px;  ">
	<img class="img-responsive center-block" src="{% static "img/timg.jpg" %}" style="height: 100px; width: 100px;border-radius: 100px;"/>
	<h3 style="text-align: center;color: #F7F7F7;">Deku德酷</h3>
</div>
<div class="container ">
	<h2 style="text-align: center;color: #F7F7F7;margin-bottom: 100px;">欢迎使用Deku便签</h2><a class="btn btn-default" href="http://sighttp.qq.com/msgrd?v=1&uin=535495438">联系</a>
	<a href="{% url 'index:home' %}" type="button" class="btn btn-default center-block tap" style="height: 50px;width: 250px;font-size: 22px;color: #31B0D5;">进入便签</a>
</div>


</body>
<script type="text/javascript" src="{% static "js/jquery-3.2.1.js" %}" ></script>
<script type="text/javascript" src="{% static "js/bootstrap.js" %}" ></script>
<script type="text/javascript">


</script>
</html>

deku/app1/templates/app1/new.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new</title>
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="{%static "css/bootstrap.css" %}" />
</head>
<body style="">
<div class="container" style="margin-top: 25%;">
    <form action="{% url 'index:add_action' %}" method="post">
        {% csrf_token %}
<div class="panel panel-primary" style="border-radius: 15px">
    <div class="panel-heading" style="padding: 0;border-radius:15px 15px 0 0;position: relative;text-align: center" >
        <div class="tip title_tip" style="position: absolute;top: 0;left: 0;height: 100%;width: 100%;">
            <h4>点击这里输入标题</h4>
        </div>

            <input type="text" name="title" value="" style="background:rgba(0,0,0,0);border: none;color: #fff;height: 43px;width: 100%;outline: none;padding-left: 20px;font-size: 18px" />
    </div>
    <div class="panel-body" style="padding: 0;position: relative;text-align: center">
        <div class="tip content_tip" style="position: absolute;top: 0;left: 0;height: 100%;width: 100%;background:rgba(1,1,1,0.2);">
            <h2 style="margin-top: 55px;">点击填写内容</h2>
        </div>
        <textarea name="content"  style="width: 100%;height: 170px;margin-bottom: -5px;overflow:hidden; resize:none; border: none;font-size: 16px;padding:10px ;" value=""></textarea>
    </div>
    <div class="panel-footer " style="border-radius: 0 0 15px 15px;text-align:center">
        <div class="checkbox pull-left " style="width: 100%;"><a class="btn btn-default" style="padding: 10px;background: #ddd;" disabled="disabled">优先级</a>
            <label ><a class="sec btn btn-default btn1">紧急</a>
                <input value="1" class="hidden" name="section" type="radio" />
            </label>
            <label ><a class="sec btn btn-default btn2">优先</a>
                <input value="2"  class="hidden" name="section" type="radio"  />
            </label>
            <label ><a class="sec btn btn-default btn3">暂缓</a>
                <input value="3"  class="hidden" name="section" type="radio" />
            </label>
        </div>
        <input class="level hidden"   type="text" name="level" value=""/>
        <input  type="text" name="type" class="hidden" value="0"/>
        <a class="btn btn-primary sub" >添加便签</a>
        <input type="submit" value="submit" class="up hidden"/>
    </div>
</div>
    </form>


</div>

</body>
<script type="text/javascript" src="{% static "js/jquery-3.2.1.js" %}" ></script>
<script type="text/javascript" src="{% static "js/bootstrap.js" %}" ></script>
<script type="text/javascript">
$(function () {
$('.tip').on('click',function(){
    $(this).hide();
    $(this).next().focus()
});
$('.btn1').on('click',function () {
    $(this).addClass('btn-danger')
    $(this).parent().siblings().find('.btn').removeClass('btn-warning btn-info')

})
    $('.btn2').on('click',function () {
    $(this).addClass('btn-warning')
    $(this).parent().siblings().find('.btn').removeClass('btn-danger btn-info')
})
    $('.btn3').on('click',function () {
    $(this).addClass('btn-info')
    $(this).parent().siblings().find('.btn').removeClass('btn-warning btn-danger')
})
$('.sub').on('click',function () {
    var i=$('.level').val()
    if(!i){
        alert('请选择优先级')
    }
    else {
        $('.up').click()
       alert('添加成功')
    }

})
    $('.sec').on('click',function () {
        var id=$(this).next().val()
        $('.level').val(id)
    })
})

</script>
</html>

deku/app1/templates/app1/tips.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <title>articles</title>
    <link rel="stylesheet" href="{%static "css/bootstrap.css" %}" />
    <style>
    </style>
</head>
<body >
    <div class="container" style="margin-top:50px;">
        {% for tip in tips %}
        <div class="tip">
            <div class="panel panel-primary">
                <input class="old_id hidden" value="{{ tip.id }}"/>
                <div class="panel-heading tip_title" data-toggle="collapse" data-target="#{{ tip.id }}">
                    {{ tip.title }}
                    <div class="btng pull-right hidden" style="    margin-top: -6px;display: flex;flex-direction: row;justify-content: space-between;">
                         <a class="btn btn-danger b_del"  style="margin-right: 5px"><span class="glyphicon glyphicon-remove"></span></a>
{#                         <a class="btn btn-info" href="" style="margin-right: 5px"><span class="glyphicon glyphicon-pencil"></span></a>#}
                         <a class="btn btn-success b_done" ><span class="glyphicon glyphicon-ok"></span></a>
                     </div>
                </div>
                <div id="{{ tip.id }}" class="collapse">
                  <div class="panel-footer">
                    {{ tip.content }}
                  </div>
                  </div>
                </div>
        </div>
        {% endfor %}
            <form class="hidden" action="{% url 'index:del_action1' %}" method="post">
                    {% csrf_token %}
                    <input class="new_id" type="text" name="del_id" value=""/>
                    <input class="del_sub" type="submit"/>
                </form>
             <form class="hidden" action="{% url 'index:done_action1' %}" method="post">
                    {% csrf_token %}
                    <input class="new_id1" type="text" name="done_id" value=""/>
                    <input class="done_sub" type="submit"/>
                </form>

    </div>



</body>
<script type="text/javascript" src="{% static "js/jquery-3.2.1.js" %}" ></script>
<script type="text/javascript" src="{% static "js/bootstrap.js" %}" ></script>
<script type="text/javascript">


        $('.tip_title').on('click',function(){
            $(this).find('.btng').toggleClass('hidden')
        })
 $('.b_del').on('click',function () {
        var i=$('.old_id').val()
        $('.new_id').val(i)
        var a=$('.new_id')
        if(!a){
            alert('删除失败，请联系作者')
        }
        $('.del_sub').click()
    })

    $('.b_done').on('click',function(){
        var i=$('.old_id').val()
        $('.new_id1').val(i)
        $('.done_sub').click()
    })
</script>
</html>

deku/app1/templates/app1/tips_done.html
{% load static %}
<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <title>articles</title>
    <link rel="stylesheet" href="{%static "css/bootstrap.css" %}" />
    <style>
    </style>
</head>
<body >
    <div class="container" style="margin-top:50px;">
        {% for tip in tips %}
        <div class="tip">
            <div class="panel panel-default">
                <div class="panel-heading tip_title" data-toggle="collapse" data-target="#{{ tip.id }}">
                    {{ tip.title }}
                    <div class="btng pull-right hidden" style="    margin-top: -6px;display: flex;flex-direction: row;justify-content: space-between;">
                         <a class="btn btn-danger b_del"  style="margin-right: 5px"><span class="glyphicon glyphicon-remove"></span></a>
                    <input class="old_id hidden" value="{{ tip.id }}"/>
                     </div>
                </div>
                <div id="{{ tip.id }}" class="collapse">
                  <div class="panel-footer">
                    {{ tip.content }}
                  </div>
                  </div>
                </div>
        </div>
        {% endfor %}
                <form class="hidden" action="{% url 'index:del_action'  %}" method="post">
                    {% csrf_token %}
                    <input class="new_id" type="text" name="del_id" value=""/>
                    <input class="del_sub" type="submit"/>
                </form>

    </div>



</body>
<script type="text/javascript" src="{% static "js/jquery-3.2.1.js" %}" ></script>
<script type="text/javascript" src="{% static "js/bootstrap.js" %}" ></script>
<script type="text/javascript">


        $('.tip_title').on('click',function(){
            $(this).find('.btng').toggleClass('hidden')
        })

    $('.b_del').on('click',function () {
        var i=$('.old_id').val()
        $('.new_id').val(i)
        var a=$('.new_id')
        if(!a){
            alert('删除失败，请联系作者')
        }
        $('.del_sub').click()
    })
</script>
</html>